title: "BUILD Beyond"
description: "Dream Bigger. BUILD Beyond."
baseurl: ""
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# SCSS settings
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include files
include:
  - _pages