title: "BUILD Beyond"
description: "Dream Bigger. BUILD Beyond."
baseurl: "/BUILDBeyondClub"
url: "https://buildbeyonddev.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# SCSS settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - style.css
  - script.js

# Force Jekyll processing
future: true
unpublished: false